// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium1.Models;

namespace kolokwium1.Migrations
{
    [DbContext(typeof(s20613Context))]
    partial class s20613ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kolokwium1.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("NeedSpecialEquipment")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction")
                        .HasName("Action_pk");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("kolokwium1.Models.Firefighter", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFirefighter")
                        .HasName("firefighter_pk");

                    b.ToTable("Firefighter");
                });

            modelBuilder.Entity("kolokwium1.Models.FirefighterAction", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFirefighter")
                        .HasColumnType("int");

                    b.HasKey("IdAction", "IdFirefighter")
                        .HasName("Firefighteraction_pk");

                    b.HasIndex("IdFirefighter");

                    b.ToTable("Firefighter_action");
                });

            modelBuilder.Entity("kolokwium1.Models.Firetruck", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperationalNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<byte>("SpecialEquipment")
                        .HasColumnType("tinyint");

                    b.HasKey("IdFireTruck")
                        .HasName("firetruck_pk");

                    b.ToTable("Firetruck");
                });

            modelBuilder.Entity("kolokwium1.Models.FiretruckAction", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFireTruck")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFireTruckAction")
                        .HasColumnType("int");

                    b.HasKey("IdAction", "IdFireTruck")
                        .HasName("Firetruck_action_pk");

                    b.HasIndex("IdFireTruck");

                    b.ToTable("Firetruck_action");
                });

            modelBuilder.Entity("kolokwium1.Models.FirefighterAction", b =>
                {
                    b.HasOne("kolokwium1.Models.Action", "Action")
                        .WithMany("FirefighterActions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium1.Models.Firefighter", "Firefighter")
                        .WithMany("FirefighterActions")
                        .HasForeignKey("IdFirefighter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("kolokwium1.Models.FiretruckAction", b =>
                {
                    b.HasOne("kolokwium1.Models.Action", "Action")
                        .WithMany("FiretruckActions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium1.Models.Firetruck", "Firetruck")
                        .WithMany("FiretruckActions")
                        .HasForeignKey("IdFireTruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Firetruck");
                });

            modelBuilder.Entity("kolokwium1.Models.Action", b =>
                {
                    b.Navigation("FirefighterActions");

                    b.Navigation("FiretruckActions");
                });

            modelBuilder.Entity("kolokwium1.Models.Firefighter", b =>
                {
                    b.Navigation("FirefighterActions");
                });

            modelBuilder.Entity("kolokwium1.Models.Firetruck", b =>
                {
                    b.Navigation("FiretruckActions");
                });
#pragma warning restore 612, 618
        }
    }
}
